//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSLTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class InputSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static InputSettings defaultInstance = ((InputSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InputSettings())));
        
        public static InputSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection xsltFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["xsltFiles"]));
            }
            set {
                this["xsltFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection inputFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["inputFiles"]));
            }
            set {
                this["inputFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string xsltDir {
            get {
                return ((string)(this["xsltDir"]));
            }
            set {
                this["xsltDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inputFilesDir {
            get {
                return ((string)(this["inputFilesDir"]));
            }
            set {
                this["inputFilesDir"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.840.1.113883.4.349.2")]
        public string HCID {
            get {
                return ((string)(this["HCID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("810 Vermont Avenue, NW")]
        public string _HomeCommunity_Address_StreetLine1 {
            get {
                return ((string)(this["_HomeCommunity_Address_StreetLine1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Washington")]
        public string _HomeCommunity_Address_City {
            get {
                return ((string)(this["_HomeCommunity_Address_City"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DC")]
        public string _HomeCommunity_Address_State {
            get {
                return ((string)(this["_HomeCommunity_Address_State"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20420")]
        public string _HomeCommunity_Address_Zip {
            get {
                return ((string)(this["_HomeCommunity_Address_Zip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("US")]
        public string _HomeCommunity_Address_Country {
            get {
                return ((string)(this["_HomeCommunity_Address_Country"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("810 Vermont Avenue, NW")]
        public string _LegalAuthenticator_Address_StreetLine1 {
            get {
                return ((string)(this["_LegalAuthenticator_Address_StreetLine1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Washington")]
        public string _LegalAuthenticator_Address_City {
            get {
                return ((string)(this["_LegalAuthenticator_Address_City"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DC")]
        public string _LegalAuthenticator_Address_State {
            get {
                return ((string)(this["_LegalAuthenticator_Address_State"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20420")]
        public string _LegalAuthenticator_Address_Zip {
            get {
                return ((string)(this["_LegalAuthenticator_Address_Zip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("US")]
        public string _LegalAuthenticator_Address_Country {
            get {
                return ((string)(this["_LegalAuthenticator_Address_Country"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InterSystems")]
        public string _LegalAuthenticator_Name_Family {
            get {
                return ((string)(this["_LegalAuthenticator_Name_Family"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HealthShare... JK, LMAO. OMG")]
        public string _LegalAuthenticator_Name_Given {
            get {
                return ((string)(this["_LegalAuthenticator_Name_Given"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(800) 497-5428")]
        public string _HomeCommunity_Telecom_WorkPhone {
            get {
                return ((string)(this["_HomeCommunity_Telecom_WorkPhone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(800) 583-8725")]
        public string _LegalAuthenticator_Telecom_WorkPhone {
            get {
                return ((string)(this["_LegalAuthenticator_Telecom_WorkPhone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.840.1.113883.4.349")]
        public string AssigningAuthority {
            get {
                return ((string)(this["AssigningAuthority"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string _VHIE_MHV_HoldTime_EncounterNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_EncounterNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_ConsultNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_ConsultNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_DischargeNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_DischargeNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_HPNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_HPNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_LabResults {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_LabResults"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_ClinicalProcNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_ClinicalProcNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_Problems {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_Problems"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string _VHIE_MHV_HoldTime_RadiologyNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_RadiologyNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_PathologyNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_PathologyNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string _VHIE_MHV_HoldTime_SurgeryNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_SurgeryNotes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string _VHIE_MHV_HoldTime_CompPenNotes {
            get {
                return ((string)(this["_VHIE_MHV_HoldTime_CompPenNotes"]));
            }
        }
    }
}
