//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSLTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class InputSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static InputSettings defaultInstance = ((InputSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InputSettings())));
        
        public static InputSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection xsltFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["xsltFiles"]));
            }
            set {
                this["xsltFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection inputFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["inputFiles"]));
            }
            set {
                this["inputFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string xsltDir {
            get {
                return ((string)(this["xsltDir"]));
            }
            set {
                this["xsltDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inputFilesDir {
            get {
                return ((string)(this["inputFilesDir"]));
            }
            set {
                this["inputFilesDir"] = value;
            }
        }
    }
}
